spring:
  datasource:

    url: jdbc:mariadb://192.0.5.19:3306/cwi;
    driver-class-name: org.mariadb.jdbc.Driver
    username: cwi
    password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true